### ISSUE TITLE
Heroku app not launching

### ISSUE THREAD

**Issue by joshvtech** [Bappy0X/my-website#1]
Heroku app won't launch due to dotenv dependency.
`ModuleNotFoundError: No module named 'dotenv'`
[Heroku Log Image](https://file.coffee/u/0aE6dpbnArJ.png)

**Comment by Bappy0X** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add `dotenv` dependency to requirements](https://trello.com/c/TAr76ik6/28-add-dotenv-dependency-to-requirements)

**Comment by joshvtech** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add `python-dotenv` dependency to requirements](https://trello.com/c/TAr76ik6/28-add-python-dotenv-dependency-to-requirements)

**Comment by joshvtech** [comment]
Heroku shouldn't use .env though, 
- [x] Copy local .env vars to Heroku stage.
- [x] Redeploy and test.

**Comment by joshvtech** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move local .env vars to Heroku stage config vars](https://trello.com/c/kJqhm3gh/29-move-local-env-vars-to-heroku-stage-config-vars)

**Comment by Bappy0X** [comment]
Issue resolved in #c3c9b20681a1730974d55ac51c7fcb4a2a35cd7d

**Comment by joshvtech** [comment]
Fixed in commit linked [Here](https://github.com/Bappy0X/my-website/commit/c3c9b20681a1730974d55ac51c7fcb4a2a35cd7d).
